# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         xPL-Perl
version:      0.01
version_from: lib/xPL/Base.pm
installdirs:  vendor
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
