---
items:
  - name: newconf
    type: option
  - name: username
    type: reconf
  - name: password
    type: reconf
  - name: resource
    type: option
  - name: host
  - name: port
  - name: friend
    type: option
    number: 32
